services:
  portal-paciente-prod-front:
    container_name: portal-paciente-prod-front
    image: healthd/frontend:stable
    ports:
      - "16000:80"        # host:container
    restart: always
    volumes:
      - ./dist:/usr/share/nginx/html
    networks:
      - 'portal-paciente-front-inet'
networks:
  portal-paciente-front-inet:
    ipam:
      driver: default
      config:
      - subnet: '172.60.177.0/24'
